### ISSUE TITLE
[BUG] Lots of returns causes

### ISSUE THREAD

**Issue by amcdnl** [aurbano/smart-area#5]
When you have a lot of returns and it starts scrolling the overlay and textarea are out of sync.

See: http://www.screencast.com/t/H5xCgnrM3Ubc

**Comment by aurbano** [comment]
Thanks for reporting @amcdnl, I'm trying to replicate the issue, what browser/os were you using?

**Comment by amcdnl** [comment]
Mac Chrome

**Comment by aurbano** [comment]
This issue is fixed, but I discovered another one while working on it: #10

**Comment by amcdnl** [comment]
Still doesn't work for me.  http://www.screencast.com/t/O0X4Smfet0
Also, there is no scrollbar on this one after I do it a bunch.
Chrome Mac.

**Comment by aurbano** [comment]
The scrollbar might be a different problem, I realized the plunkr was not updated, testing a bit more from windows I've seen that the fix is not 100% consistent, and pressing enter several times can stop the sync.

Will investigate further

**Comment by amcdnl** [comment]
:) ... Here is 2 other solutions I found jquery based -

http://podio.github.io/jquery-mentions-input/
https://github.com/daniel-zahariev/jquery-textntags/
